version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    steps:
      - checkout

      - run: npm install; npm install -g parcel-bundler; parcel build src/index.js
    
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      
      - add_ssh_keys: 
          fingerprints: 
            - "37:f2:a9:05:d7:9d:42:f4:d8:57:6b:3d:82:60:d3:41"
      
      - run:
          name: Deploy Over SSH
          command: |
            cp ~/project/.circleci/known_hosts ~/.ssh/
            git status
            git remote add production ssh://${USER_NAME}@${HOSTNAME}/var/repo/chrisdev.git
            git push production master
            exit
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
